spring:
  datasource:
    url: jdbc:mysql://localhost/javaFurtherStage2Module2?useUnicode=true&characterEncoding=utf8
    username: root
    password: L1178594290
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    database: 0
    host: 192.168.8.101
    port: 6379
    connectionTimeout: 5000
    password:
server:
  port: 8081
