server:
  port: 8080
spring:
  application:
    name: Myprovider
dubbo:
  registry:
    address: zookeeper://192.168.8.102:2181
  protocol:
    name: dubbo
    port: 20880
  scan:
    base-packages: com.ivan.service
